apiVersion: apps/v1
kind: Deployment
metadata:
  name: remi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: remi
  template:
    metadata:
      labels:
        app: remi
    spec:
      containers:
      - name: remi
        image: quangngoc430/remi
        ports:
        - containerPort: 8080
