name: integration-test
on: push
jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d
      - name: Wait container running
        run: while [ "`docker inspect -f {{.State.Running}} remi_app`" != "true" ]; do     sleep 2; done
      - name: Test
        run: go test -v -cover ./features/...